# Generated by Django 4.2.1 on 2023-05-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_equipo", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_de_partido", models.IntegerField()),
                (
                    "equipo_ganador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Campeonato.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="partido_x_equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goles_TR", models.IntegerField()),
                ("tarjetas_amarillas", models.IntegerField(blank=True, null=True)),
                ("tarjetas_rojas", models.IntegerField(blank=True, null=True)),
                ("penales", models.IntegerField(blank=True, null=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Campeonato.equipo",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Campeonato.partido",
                    ),
                ),
            ],
        ),
    ]
